### ISSUE TITLE
Plugin is not upgraded

### ISSUE THREAD

**Issue by vitaliybaran** [marcusgreen/moodle-qtype_gapfill#112]
**Describe the bug**
I upgraded my Moodle to 4.4+ and while upgrading I received a message that the plugin was missing from disk. (That is the usual message I receive when upgrading Moodle. I then manually install the plugin which  resolves the issue.) But this time when I tried to install the plugin manually, the installation was aborted with a message saying that a higher version of the plugin is already installed. I then tried installing from Moodle website and I got this message: "There is a request to install plugin Gapfill (qtype_gapfill) version 2024042300 from the Moodle plugins directory on this site. However, the plugin installation pre-check failed (reason code: cannotdowngrade)." 
**It should be said here** that one day earlier (before I upgraded my Moodle to v.4.4+) I received a message that there is a newer version of the plugin and I installed it.
Now I cannot uninstall the plugin as there are many questions using it in my question bank and I cannot reinstall it either. I'm paralyzed. Help!!!

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by vitaliybaran** [comment]
![image](https://github.com/marcusgreen/moodle-qtype_gapfill/assets/105056918/093967ab-3107-48ab-8ad8-783e6bb7cfbe)

**Comment by marcusgreen** [comment]
Am currently travelling, will respond later

**Comment by marcusgreen** [comment]
There was an error in the version number. The plugin version was set to 2924022000 (see the leading 29 which should be 20). The full value should be 2024042300. Do you have direct access to your database?. If you have I  can write instructions on how to update that value so the update works. My apologies for the error.

**Comment by vitaliybaran** [comment]
> There was an error in the version number. The plugin version was set to 2924022000 (see the leading 29 which should be 20). The full value should be 2024042300. Do you have direct access to your database?. If you have I can write instructions on how to update that value so the update works. My apologies for the error.

Yes, I have access to the database.

**Comment by marcusgreen** [comment]
I am working on some instructions.

**Comment by marcusgreen** [comment]
I advise creating a whole database backup if you can before doing that as it is not generally advisable to directly update the database directly. Once you are at the database command line you can update anything which could break things, but so long as you follow these instructions carefully you should be fine and the worse case scenario is a slight further mangling of the gapfill qusiton type. I am a cautious man.

If you can access your config.php it will contain some useful information on what you need to do.
So my database is mdl44 and can be found in this line

$CFG->dbname    = 'mdl44';

And the login to the database and password are as follows.
$CFG->dbuser    = 'moodle';
$CFG->dbpass    = 'password';

I am assuming you are using mysql and you can get to the mysql prompt assuming you moodle user is called moodle with the following. The -A is not strictly necessary but it will make startup quicker.

mysql -uadmin -p -A

change to the database with something like

use mdl44; // Or perhaps it is called moodle or something similar.

Run the following command and it should come back 
select * from mdl_config_plugins where plugin='qtype_gapfill' and name = 'version';

It should come back with a row containing id, plugin, name and value fields.
The value should be the number starting with 29 which is the error, as it should be 20 something someting.
If it doesn't return that you might have a different prefix instead of mdl_ so run the following 

show tables
and you will se what the prefix is. Change that select command and replace mdl_ with whatever you see.

Once you are happy it returns one row and it shows the value starting with 20 and not 29 you can run the following command which will reset the value.

update mdl_config_plugins set value = '2024042300' where plugin='qtype_gapfill' and name='version';

The purge your system from yourmoodledomain/admin/purgecaches.php
 
The check the upgrade works as expected as that the gapfill question type works.

Please confirm it has worked for you.

**Comment by vitaliybaran** [comment]
Hi Marcus, I really appreciate your involvement, but I should say that I am faaaar away from understanding mysql, command lines and stuff. I am afraid I will make it worse. I'm just a teacher who knows his way about installing and upgrading Moodle and plugins but to go as deep as command lines and database is much beyond my understanding. I never used command lines in my life. I am afraid I will mess it all up. Is there a simpler way to do it like "go there and there, open a file this and this, change this and then save"? 
Or if maybe you agreed to perform this operation for me - I could send you my config file db credentials to your email?... I'd be really greatful.

**Comment by marcusgreen** [comment]
Hi Vitaly
It is 22.32 in the evening for me and I am about to go to bed. Will you be around tomorrow to talk about this. You can email me at marcusavgreen at gmail.com  and we can set up a call or similar.

**Comment by marcusgreen** [comment]
I am confident we can get it fixed one way or another.

**Comment by vitaliybaran** [comment]
My ENORMOUS THANK YOU to Mr Marcus Green for resolving my issue. 
I don't know what I would do without your help. Your involvement and patience are priceless.
