### ISSUE TITLE
Problem with gapfill response with words with accent mark

### ISSUE THREAD

**Issue by eduhernandezm** [marcusgreen/moodle-qtype_gapfill#16]
Hi Marcus,
![screenshot_202](https://cloud.githubusercontent.com/assets/7700391/11562141/f2b63ff0-99c3-11e5-9243-9fe3a4713981.jpg)

I tell you what my problem is. I have a Moodle platform version 2.9.1, with the latest update on the type of "gapfill" question.

The platform is in Spanish, and the problem occurs when generating a question to fill in where the answers have accents (Spanish spelling), when finalizing the questionnaire fails on those responses. No hunt properly.

I've also updated the language pack "Spanish-International", but continues to this judgment when evaluating responses GapFill type.

Any suggestions or bug moodle own?

Regards

**Comment by marcusgreen** [comment]
Many thanks for your feedback, it is appreciated. I didn't understand your sentence that said "No hunt properly".  First turn off regular expression processing and send me a screen shot of what happens.

There is an issue with extended characters (e.g. accents), which is fixed in this version of the question.php file
https://github.com/marcusgreen/moodle-qtype_gapfill/blob/gapfill_1.9/question.php

Are you able to make a copy of your current version, replace with that file and let me know the result. If you still get a problem post another screen shot. I look forward to your response.

**Comment by eduhernandezm** [comment]
Marcus good again,

First of all, many thanks for the quick response.

I made the upgrade file "question.php" hosted on [moodle]/question/type/gapfill.

I performed the test again questionnaires to the type of question "gapfill" and this time, it works perfectly in recognizing the accents in words that carry.

I understand that this update will be released in the next code release of "gapfill".

I will continue to test it thoroughly test and verify that the problem is solved on all platforms I manage.

Thanks so much for the help.

Best regards

**Comment by marcusgreen** [comment]
Many thanks for your feedback, I am pleased it solved the problem. Yes I will be releasing a new version V1.9 in the near future. I intend to write the release notes this evening. There are only two things, one is this bug fix. What is your first language (I am looking for someone to translate some strings).

**Comment by eduhernandezm** [comment]
Perfect.

As to solve the problem facing me is simply to update a file, the file I sobreescribiré on all platforms where gapfill used in cuesitonarios.

I'll be awaiting the next update to have it completely updated.

My language is Spanish and I am Spanish and live in Spain.

If I can help in some string translation, ask me and we can make a partnership.

Regards.
