### ISSUE TITLE
gapfill refusing to save in Moodle 3.8

### ISSUE THREAD

**Issue by lauriehuber** [marcusgreen/moodle-qtype_gapfill#67]
Hi Marcus

I was already starting to have this problem in Moodle 3.6, so not sure if it is a Moodle version issue.

When I try to save a question, it takes a really long time (60 seconds or more).

When I try to back-up a quiz with a Gapfill question in Moodle 3.8, it just spins eternally.

I can back-up the quizzes with Gapfill from 3.6 - quickly.  The saving if I am editing one from 3.6 is slow.

It is not my internet:)  I have really high-speed and other question types are working fine.

Looking forward to you feedback.

Cheers

Laurie

**Comment by marcusgreen** [comment]
Hi Laurie, I can see it is 22 days since you posted this, my apologies for not responding sooner.If this still an issue can you contact me directly at marcusgreen at mailbox.org and I will see if we can work through the issue. I have never seen anything like this issue previously and there is nothing that springs to mind about the code that would cause such an issue.
